### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_wine-quality-predictors#10]
__Reasoning__

1. In the project proposal, you might want to explain how the integer-valued outcome of wine quality will be converted to an ordinal or categorical variable for the decision tree analysis.

2. Also, you might want to clarify whether the red and white wine date will be analyzed together with a single model or separately with their own specific classification trees.

3. For the potential imbalance of classes, it is not obvious how you can 'balance them out'. You might want to elaborate on this point if you choose to include it. Are you thinking of down sampling the over-represented classes instead of using all the data? (I am not endorsing this approach but just trying to throw out some ideas.)

__Optional__

1. I wonder if you can replace the screenshots in README with, say, an Rmarkdown style code chunk and output. Not sure if you can do this in GitHub...

__Mechanics__

1. Good job changing the title of README to a meaningful project name.

2. Please refer to your individual 'proposal repo' for comments on links, etc.

**Comment by lyiris22** [comment]
Thank you for the feedback!
We have created a new readme corresponding to the requirements for Milestone1. Our modifications according to the issues are in the old proposal.md in the doc folder. The parts related to your questions are below:

1. "Since the outcome of wine are integers, we combine the quality number into 3 or 4 targets. In the 3 targets case, the categories are "low", "med" and "high". In the 4 targets case, the categories are "low", "med_low", "med_high" and "high". We try both ways to determine which is better for fitting our decision tree." The details are in the Data Cleaning section of the report in milestone.
2. "The red wine set and white wine set will be evaluated separately."
3. "In the DecisionTreeClassifier in [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html), there is a hyper-parameter `class_weight` that we can set it to `balanced` to balance our data."

We had also made some modifications in the old proposal. The idea of the proposal is reflected in the new readme for Milestone 1.
