### ISSUE TITLE
Peer Feedback in Lab

### ISSUE THREAD

**Issue by lyiris22** [UBC-MDS/DSCI_522_wine-quality-predictors#25]
- The report is complicated in choosing the 3-target or 4-target data to analyze. Better to use a more concise way to represent.
- Can add a file structure portion to the readme.
- Try to standardize the data before we fit the decision tree.
- State that all the features are used when we fit the decision tree.

(Discussed with: Weifeng Guo and Linyang Yu)

**Comment by reza-bagheri** [comment]
- I think we cannot delete the figures of 3-target and 4-target or make the text shorter, but I can add a few lines to give some clarifications on why we did this. I can also address the comments that I received this way.
- I think standardization does make a big difference since we balanced the data.
- I will also add a few lines to explain that we used all the features to fit the decision tree.

**Comment by lyiris22** [comment]
Thank you for the feedback Reza. For the file structure, I will add that part into the readme file.
Also, do you mean by "doesn't make a big difference" in the second line? It looks like a small typo.

**Comment by reza-bagheri** [comment]
I fixed it. I have revised the report with a new table for features. Please take a look

**Comment by lyiris22** [comment]
I have checked that, it looks good.
All the issues here are responded, more details lies in [the string of TA's issue](https://github.com/UBC-MDS/DSCI_522_wine-quality-predictors/issues/27).
