### ISSUE TITLE
Feedback from other groups in the lab

### ISSUE THREAD

**Issue by reza-bagheri** [UBC-MDS/DSCI_522_wine-quality-predictors#26]
I talked to some people from other groups and received some good comments:
The main question was that why we tried different methods for data cleaning and was it part of the main question or not?
My answer is that we did not really know what the best method is for data cleaning, so we had to try different methods.
They asked if we want to rephrase the question and include some comments about the data cleaning or not? I personally do not think that we should do it that way, but maybe we can add some comments to the final report and mention that this was a kind of try and error process, and we wanted to try different thing to see how they affect the final results.

**Comment by lyiris22** [comment]
It seems you already have a good answer to the questions in the feedback. Since I had also received suggestions to clarify the method-choosing part of our report, maybe we can add some descriptions to make it clearer.
We can also wait and see if there is related advices from the Issues by TA, so we can combine them together to make some improvements.
